import Head from 'next/head'

import styles from '../styles/Home.module.css'
import {signIn, signOut, useSession} from "next-auth/react"

export default function Home() {
  const { data: session } = useSession();

  const SignedInComponent = () => {
    return (
        <>
          Signed in as {session.user.email} <br />
          <div>You can now acces our super secret pages</div>

          <button onClick={() => signOut()}>Sign out</button>
        </>
    );
  };

  const SignedOutComponent = () => {
    return (
        <>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </>
    );
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <main className={styles.main}>
        {session && <SignedInComponent />}
        {!session && <SignedOutComponent />}
      </main>
    </div>
  )
}
